### PR TITLE
MADE IT 100 TIMES BETTER BY DELETING IT

### PR DESCRIPTION
**Pull request by betterclient**

### CODE REVIEW

**Comment by Quexii** [comment]
**damn good job on this, must have been hard to pull of!**

**Comment by betterclient** [comment]
yes it was hard

**Comment by ImNotStealth** [comment]
well written! it'll prob get a few hundred fps with all these optimizations ! ! !

**Comment by betterclient** [comment]
it gets infinite by not existing !!!

**Pull request closed without merging**
